/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmailVerifiedRouteImport } from './routes/email-verified'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDeveloperIndexRouteImport } from './routes/_authenticated/developer.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties.new'
import { Route as AuthenticatedDeveloperTeamRouteImport } from './routes/_authenticated/developer.team'
import { Route as AuthenticatedDeveloperProjectsRouteImport } from './routes/_authenticated/developer.projects'
import { Route as AuthenticatedDeveloperProfileRouteImport } from './routes/_authenticated/developer.profile'
import { Route as AuthenticatedDeveloperMarketingRouteImport } from './routes/_authenticated/developer.marketing'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin.listings'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated/admin.agents'
import { Route as AuthenticatedPropertiesIdEditRouteImport } from './routes/_authenticated/properties.$id.edit'
import { Route as AuthenticatedDeveloperProjectsNewRouteImport } from './routes/_authenticated/developer.projects.new'
import { Route as AuthenticatedDeveloperProjectsIdRouteImport } from './routes/_authenticated/developer.projects.$id'

const EmailVerifiedRoute = EmailVerifiedRouteImport.update({
  id: '/email-verified',
  path: '/email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperIndexRoute =
  AuthenticatedDeveloperIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperTeamRoute =
  AuthenticatedDeveloperTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperProjectsRoute =
  AuthenticatedDeveloperProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperProfileRoute =
  AuthenticatedDeveloperProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperMarketingRoute =
  AuthenticatedDeveloperMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPropertiesIdEditRoute =
  AuthenticatedPropertiesIdEditRouteImport.update({
    id: '/properties/$id/edit',
    path: '/properties/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeveloperProjectsNewRoute =
  AuthenticatedDeveloperProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDeveloperProjectsRoute,
  } as any)
const AuthenticatedDeveloperProjectsIdRoute =
  AuthenticatedDeveloperProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDeveloperProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/developer': typeof AuthenticatedDeveloperRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/developer/marketing': typeof AuthenticatedDeveloperMarketingRoute
  '/developer/profile': typeof AuthenticatedDeveloperProfileRoute
  '/developer/projects': typeof AuthenticatedDeveloperProjectsRouteWithChildren
  '/developer/team': typeof AuthenticatedDeveloperTeamRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/developer/projects/$id': typeof AuthenticatedDeveloperProjectsIdRoute
  '/developer/projects/new': typeof AuthenticatedDeveloperProjectsNewRoute
  '/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/developer/marketing': typeof AuthenticatedDeveloperMarketingRoute
  '/developer/profile': typeof AuthenticatedDeveloperProfileRoute
  '/developer/projects': typeof AuthenticatedDeveloperProjectsRouteWithChildren
  '/developer/team': typeof AuthenticatedDeveloperTeamRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/developer': typeof AuthenticatedDeveloperIndexRoute
  '/developer/projects/$id': typeof AuthenticatedDeveloperProjectsIdRoute
  '/developer/projects/new': typeof AuthenticatedDeveloperProjectsNewRoute
  '/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/email-verified': typeof EmailVerifiedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/developer/marketing': typeof AuthenticatedDeveloperMarketingRoute
  '/_authenticated/developer/profile': typeof AuthenticatedDeveloperProfileRoute
  '/_authenticated/developer/projects': typeof AuthenticatedDeveloperProjectsRouteWithChildren
  '/_authenticated/developer/team': typeof AuthenticatedDeveloperTeamRoute
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/_authenticated/developer/projects/$id': typeof AuthenticatedDeveloperProjectsIdRoute
  '/_authenticated/developer/projects/new': typeof AuthenticatedDeveloperProjectsNewRoute
  '/_authenticated/properties/$id/edit': typeof AuthenticatedPropertiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/email-verified'
    | '/admin'
    | '/dashboard'
    | '/developer'
    | '/properties/$id'
    | '/properties/'
    | '/admin/agents'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/listings'
    | '/admin/reports'
    | '/admin/users'
    | '/developer/marketing'
    | '/developer/profile'
    | '/developer/projects'
    | '/developer/team'
    | '/properties/new'
    | '/admin/'
    | '/developer/'
    | '/developer/projects/$id'
    | '/developer/projects/new'
    | '/properties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/email-verified'
    | '/dashboard'
    | '/properties/$id'
    | '/properties'
    | '/admin/agents'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/listings'
    | '/admin/reports'
    | '/admin/users'
    | '/developer/marketing'
    | '/developer/profile'
    | '/developer/projects'
    | '/developer/team'
    | '/properties/new'
    | '/admin'
    | '/developer'
    | '/developer/projects/$id'
    | '/developer/projects/new'
    | '/properties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/email-verified'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/developer'
    | '/properties/$id'
    | '/properties/'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/listings'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/_authenticated/developer/marketing'
    | '/_authenticated/developer/profile'
    | '/_authenticated/developer/projects'
    | '/_authenticated/developer/team'
    | '/_authenticated/properties/new'
    | '/_authenticated/admin/'
    | '/_authenticated/developer/'
    | '/_authenticated/developer/projects/$id'
    | '/_authenticated/developer/projects/new'
    | '/_authenticated/properties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmailVerifiedRoute: typeof EmailVerifiedRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/email-verified': {
      id: '/email-verified'
      path: '/email-verified'
      fullPath: '/email-verified'
      preLoaderRoute: typeof EmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/': {
      id: '/_authenticated/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof AuthenticatedDeveloperIndexRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/team': {
      id: '/_authenticated/developer/team'
      path: '/team'
      fullPath: '/developer/team'
      preLoaderRoute: typeof AuthenticatedDeveloperTeamRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/projects': {
      id: '/_authenticated/developer/projects'
      path: '/projects'
      fullPath: '/developer/projects'
      preLoaderRoute: typeof AuthenticatedDeveloperProjectsRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/profile': {
      id: '/_authenticated/developer/profile'
      path: '/profile'
      fullPath: '/developer/profile'
      preLoaderRoute: typeof AuthenticatedDeveloperProfileRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/marketing': {
      id: '/_authenticated/developer/marketing'
      path: '/marketing'
      fullPath: '/developer/marketing'
      preLoaderRoute: typeof AuthenticatedDeveloperMarketingRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/properties/$id/edit': {
      id: '/_authenticated/properties/$id/edit'
      path: '/properties/$id/edit'
      fullPath: '/properties/$id/edit'
      preLoaderRoute: typeof AuthenticatedPropertiesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer/projects/new': {
      id: '/_authenticated/developer/projects/new'
      path: '/new'
      fullPath: '/developer/projects/new'
      preLoaderRoute: typeof AuthenticatedDeveloperProjectsNewRouteImport
      parentRoute: typeof AuthenticatedDeveloperProjectsRoute
    }
    '/_authenticated/developer/projects/$id': {
      id: '/_authenticated/developer/projects/$id'
      path: '/$id'
      fullPath: '/developer/projects/$id'
      preLoaderRoute: typeof AuthenticatedDeveloperProjectsIdRouteImport
      parentRoute: typeof AuthenticatedDeveloperProjectsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDeveloperProjectsRouteChildren {
  AuthenticatedDeveloperProjectsIdRoute: typeof AuthenticatedDeveloperProjectsIdRoute
  AuthenticatedDeveloperProjectsNewRoute: typeof AuthenticatedDeveloperProjectsNewRoute
}

const AuthenticatedDeveloperProjectsRouteChildren: AuthenticatedDeveloperProjectsRouteChildren =
  {
    AuthenticatedDeveloperProjectsIdRoute:
      AuthenticatedDeveloperProjectsIdRoute,
    AuthenticatedDeveloperProjectsNewRoute:
      AuthenticatedDeveloperProjectsNewRoute,
  }

const AuthenticatedDeveloperProjectsRouteWithChildren =
  AuthenticatedDeveloperProjectsRoute._addFileChildren(
    AuthenticatedDeveloperProjectsRouteChildren,
  )

interface AuthenticatedDeveloperRouteChildren {
  AuthenticatedDeveloperMarketingRoute: typeof AuthenticatedDeveloperMarketingRoute
  AuthenticatedDeveloperProfileRoute: typeof AuthenticatedDeveloperProfileRoute
  AuthenticatedDeveloperProjectsRoute: typeof AuthenticatedDeveloperProjectsRouteWithChildren
  AuthenticatedDeveloperTeamRoute: typeof AuthenticatedDeveloperTeamRoute
  AuthenticatedDeveloperIndexRoute: typeof AuthenticatedDeveloperIndexRoute
}

const AuthenticatedDeveloperRouteChildren: AuthenticatedDeveloperRouteChildren =
  {
    AuthenticatedDeveloperMarketingRoute: AuthenticatedDeveloperMarketingRoute,
    AuthenticatedDeveloperProfileRoute: AuthenticatedDeveloperProfileRoute,
    AuthenticatedDeveloperProjectsRoute:
      AuthenticatedDeveloperProjectsRouteWithChildren,
    AuthenticatedDeveloperTeamRoute: AuthenticatedDeveloperTeamRoute,
    AuthenticatedDeveloperIndexRoute: AuthenticatedDeveloperIndexRoute,
  }

const AuthenticatedDeveloperRouteWithChildren =
  AuthenticatedDeveloperRoute._addFileChildren(
    AuthenticatedDeveloperRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRouteWithChildren
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedPropertiesIdEditRoute: typeof AuthenticatedPropertiesIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRouteWithChildren,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedPropertiesIdEditRoute: AuthenticatedPropertiesIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EmailVerifiedRoute: EmailVerifiedRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
